config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #resources :groups do
   # resources :students
  #end
  root 'sessions#new'
  post '/login' => 'sessions#create'
  get '/show' => 'sessions#show'
  resources :groups
  delete '/logout' => 'sessions#destroy'
  get '/show/new' => 'groups#new'
  resources :groups
  post '/show/new' => 'groups#create'
  get '/show/show' => 'groups#show'
  get '/groups/:id/new' => 'students#new'
  get '/groups/:id' => 'groups#show', as: :show_group
  resources :students, :groups
  post '/groups/:id/create' => 'students#create', as: :create_student
  get '/student/:id' => 'package#show', as: :package
  get '/student/:id/show' => 'package#index'
  put '/student/:id/show' => 'package#update', as: :update
  get '/groups/:id/email' => 'students#email'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :students, dependent: :destroy
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :group#, optional: true
	#accepts_nested_attributes_for :group
	before_create :super_string

	def super_string
		#if (self.base_agradecimiento && self.base_agradecimiento_color && self.base_agradecimiento_3d && self.base_agradecimiento_tamaño) |= nil do
			self.base_agradecimiento_final = self.base_agradecimiento + " " + self.base_agradecimiento_color + ' ' + self.base_agradecimiento_3d + ' ' + self.base_agradecimiento_tamaño + ' ' + self.base_agradecimiento_fondo
		#end
		self.base_diploma_final = self.base_diploma + " " + self.base_diploma_color + ' ' + self.base_diploma_3d + ' ' + self.base_diploma_tamaño + ' ' + self.base_diploma_fondo
		self.base_foto_final = self.base_foto + " " + self.base_foto_color + ' ' + self.base_foto_3d + ' ' + self.base_foto_tamaño + ' ' + self.base_foto_fondo
		self.placa_agradecimiento_final = self.placa_agradecimiento + " " + self.placa_agradecimiento_color
		self.placa_diploma_final = self.placa_diploma + " " + self.placa_diploma_color
		self.placa_foto_final = self.placa_foto + " " + self.placa_foto_color
		self.placa_agradecimiento_final = self.anillo + " " + self.anillo_tamaño
	end

	before_save do |student|
		student.name = student.name.downcase.titleize
		student.email = student.email.downcase
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user

  
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def require_user
    redirect_to '/' unless current_user
  end

  def logged_user
    if current_user 
      redirect_to '/show' 
    end
  end

  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :require_user

	def new
		@group = Group.new
	end

	def create
		@group = Group.new(group_params)
		if @group.save
			redirect_to '/show'
		else
			redirect_to '/show/new'
			flash[:invalid_group] = 'Por favor completa la información'
		end
	end

	def show
		@group = Group.find(params[:id])
		@students = @group.students
	end

	def destroy
		@group = Group.find(params[:id])
		@group.destroy
		redirect_to '/show'
	end

	private
	def group_params
		params.require(:group).permit(:university, :degree, :representative, :generation)
	end

end

app/controllers/package_controller.rb
class PackageController < ApplicationController
	before_action :require_user

	def show
		@student = Student.find(params[:id])
	end

	def index
		@student = Student.find(params[:id])
		@group = Group.find(@student.group_id)
		@paquete = {
			base: {
				color: ['Verde','Negro', 'Chocolate', 'Caoba'],
				fondo: ['F/Yute', 'F/Beige', 'F/Negro', 'F/Cristal'],
				tipo: ['Jirafa', 'Petatillo', 'Estrella'],
				tamaño: ['Doble', 'Triple'],
				placa: {
					tipo: ['Normal', 'Con Corte', 'Berlin', 'Curvas'],
					color: ['Chocolate', 'Marfin', 'Oro Cepillado Arena Chocolate']	
					}
				},
			anillo: {
				nombre: ['alianza rectangular', 'alianza engarzado'],
				tamaño: [1,2,3,4,5,6,7,8,9,10,11,12]
				}
			}
	end

	def update
	end

	private
	def student_params
		params.require(:student).permit(:name, :email, :cellphone, :base_agradecimiento, :base_agradecimiento_color, 
			:base_agradecimiento_3d, :base_agradecimiento_tamaño, :base_agradecimiento_fondo, :placa_agradecimiento, :base_diploma, :base_diploma_color,
			:base_diploma_3d, :base_diploma_tamaño, :base_diploma_fondo, :placa_diploma, :base_foto, :base_foto_color, :base_foto_3d, :base_foto_tamaño, :base_foto_fondo,
			:placa_foto, :anillo, :anillo_tamaño, :regalo1, :regalo2, :regalo3, :regalo4, :group_id, :placa_agradecimiento_color, :placa_diploma_color,
			:placa_foto_color)
	end

	private
	def group_params
		params.require(:group).permit(:university, :degree, :representative, :generation)
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :logged_user, only: [:new, :create]
	before_action :require_user, except: [:new, :create]
	def new
	end

	def create
		@user = User.find_by_email(params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			redirect_to '/show'
		else
			redirect_to '/'
			flash[:invalid_login] = "Your email or password is incorrect"
		end
	end

	def show
		@groups = Group.all.order(:representative)
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/'
	end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :require_user

	def new
		@student = Student.new
		@group = Group.find(params[:id])
		@paquete = {
			base: {
				color: [nil,'blue', 'black', 'bitch'],
				fondo: [nil,'F/Yute', 'F/Beige', 'F/Negro', 'F/Cristal'],
				tipo: [nil,'Jirafa', 'Petatillo', 'Estrella'],
				tamaño: [nil,'Doble', 'Triple'],
				placa: {
					tipo: [nil,'Normal', 'Con Corte'],
					color: [nil,'Chocolate', 'Marfin']	
					}
				},
			anillo: {
				nombre: [nil,'alianza rectangular', 'pedro y pablo'],
				tamaño: [nil,1,2,3,4,5,6,7,8,9,10,11,12]
				}
			}
	end

	def create
		@group = Group.new
		@group = Group.find(params[:id])
		@student = Student.new(student_params)

		if @student.save!
			redirect_to show_group_path
		else
			render 'new'
		end
	end

	def show
		@group = Group.find(params[:id])
		@students = @group.students
		@base_agradecimiento = @students.select(:base_agradecimiento_final).group(:base_agradecimiento_final).having("count(*) > 0").count
		@base_diploma = @students.select(:base_diploma_final).group(:base_diploma_final).having("count(*) > 0").count
		@base_foto = @students.select(:base_foto_final).group(:base_foto_final).having("count(*) > 0").count
	end


	def email
	end


	private
	def student_params
		params.require(:student).permit(:name, :email, :cellphone, :base_agradecimiento, :base_agradecimiento_color, 
			:base_agradecimiento_3d, :base_agradecimiento_tamaño, :base_agradecimiento_fondo, :placa_agradecimiento, :base_diploma, :base_diploma_color,
			:base_diploma_3d, :base_diploma_tamaño, :base_diploma_fondo, :placa_diploma, :base_foto, :base_foto_color, :base_foto_3d, :base_foto_tamaño, :base_foto_fondo,
			:placa_foto, :anillo, :anillo_tamaño, :regalo1, :regalo2, :regalo3, :regalo4, :group_id, :placa_agradecimiento_color, :placa_diploma_color,
			:placa_foto_color)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/package_helper.rb
module PackageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/groups/new.html.erb
<div class="new_group">
	<div class="container">
		<% if flash[:invalid_group] %>
		<p class="invalid_group"><%= flash[:invalid_group]%></p>
		<% end %>
		<h2>Agrega un nuevo Grupo a la Base de Datos</h2>
		<%= form_for(@group) do |f| %>
		<%= f.text_field :university, :required => 'required', :placeholder => 'Universidad' %><br>
		<%= f.text_field :generation, :required => 'required', :placeholder => 'Generación' %><br>
		<%= f.text_field :degree, :required => 'required', :placeholder => 'Carrera' %><br>
		<%= f.text_field :representative, :required => 'required', :placeholder => 'Representante' %><br>
		<%= f.submit 'Guardar'%>
		<% end %>
	</div>
</div>

app/views/groups/show.html.erb
<div class="group_students">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h3 align="center" style="color: black; margin-top: 1.5em;"><span style="color: steelblue;"><%= @group.degree.titleize %></span> <%=@group.representative.titleize %></h3>
			</div>
		</div>
		<div class="row main">
			<div class="col-md-8">
				<p class="titulo">Seleccione un graduado para ver o editar su pedido</p>
				<% @students.each_with_index do |s, index| %>
				<%= link_to package_path(s) do %>
				<p class="graduado"><%= index+1 %>.-  <span><%= s.name %></span><span class="pull-right"><%= s.email %></span></p>
				<% end %>
				<% end %>
			</div>
			<div class="col-md-4 links">
				<%= link_to 'Agregar Pedido', {controller: 'students', action: 'new'}, :class => 'link' %>
				<%= link_to 'Generar Hoja de Material', {controller: 'students', action: 'show'}, :class => 'link material' %>
				<%= link_to 'Mandar Email', {controller: 'students', action: 'email'}, :class => 'link email' %>
				<%= link_to 'Eliminar Grupo', group_path(@group), method: 'delete', :class => 'link delete', data: {confirm: 'Seguro que desea eliminar el grupo y todos sus graduados?'} %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memories</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif|Lato" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<div class="header">
  		<div class="container">
        <div class="row">
          <div class="col-md-4 col-xs-6">
      			<a href="/show"><h1><span style="color: steelblue;">M</span>emorie's</h1></a>           
          </div>
          <div class="col-md-8 col-xs-6">
            <% if current_user %>
            <ul class="pull-right">
              <li> <%= current_user.name %></li>
              <li> <%= link_to 'Salir', logout_path, method: 'delete', class: 'salir' %></li>
            </ul>
            <% end %>
          </div>
        </div>
  		</div>
  	</div>

    <%= yield %>

    <div class="footer">
    	<div class="container">
    		<h4>Desarrollado por &copy; Luis Arturo Nieto</h4>
    	</div>
    </div>

  </body>
</html>

app/views/package/index.html.erb
<div class="actualizar_pedido">
	<div class="container">
		<h2>Editar pedido de <%= @student.name %> del grupo de <%= link_to @group.representative.titleize, show_group_path %></h2>
		
		<%= form_for(@student, url: update_path) do |f| %>
		
		<div class="row">
			<div class="col-md-12">				
				<span><%= f.text_field :name, :required => 'required', :placeholder => 'Nombre', :class => 'nombre' %><br>
				<%= f.email_field :email, :required => 'required', :placeholder => 'Email' %>
				<%= f.text_field :cellphone, :placeholder => 'Celular' %><br></span>
			</div>
		</div>
		
		<div class="row first main">
			<div class="col-md-6">
				<h3>Agradecimiento</h3>
				<p>Seleccione la base de la Agradecimiento:</p>
				<%= f.select(:base_agradecimiento, options_for_select(@paquete[:base][:tipo].each do |x| [x] end, selected = @student.base_agradecimiento)) %>			
				<p>Seleccione el color de la Base:</p>
				<%= f.select(:base_agradecimiento_color, options_for_select(@paquete[:base][:color].each do |x| [x] end, selected = @student.base_agradecimiento_color)) %>
				<p>Seleccione el tamaño de la Base:</p>			
				<%= f.select(:base_agradecimiento_tamaño, options_for_select(@paquete[:base][:tamaño].each do |x| [x] end)) %>
				<p>Seleccione el fondo de la Base:</p>
				<%= f.select(:base_agradecimiento_fondo, options_for_select(@paquete[:base][:fondo].each do |x| [x] end)) %>
				<p>Seleccione si la base es Plana o 3D:</p>
				<%= f.radio_button :base_agradecimiento_3d, '' %>
				<%= f.label :base_agradecimiento_3d, 'Plana', :value => '' %>
				<%= f.radio_button :base_agradecimiento_3d, '3D' %>
				<%= f.label :base_agradecimiento_3d, '3D', :value => '3D' %>
			</div>
			<div class="col-md-6">
				<h5>Placa Agradecimiento</h5>
				<p>Seleccione el Tipo de Placa:</p>
				<%= f.select(:placa_agradecimiento, options_for_select(@paquete[:base][:placa][:tipo].each do |x| [x] end)) %>
				<p>Seleccione el Color de Placa:</p>
				<%= f.select(:placa_agradecimiento_color, options_for_select(@paquete[:base][:placa][:color].each do |x| [x] end)) %>
			</div>
		</div>
		

		<div class="row main">
			<div class="col-md-6">
				<h3>Diploma</h3>
				<p>Seleccione la base del Diploma:</p>
				<%= f.select(:base_diploma, options_for_select(@paquete[:base][:tipo].each do |x| [x] end)) %>			
				<p>Seleccione el color de la Base:</p>
				<%= f.select(:base_diploma_color, options_for_select(@paquete[:base][:color].each do |x| [x] end)) %>
				<p>Seleccione el tamaño de la Base:</p>			
				<%= f.select(:base_diploma_tamaño, options_for_select(@paquete[:base][:tamaño].each do |x| [x] end)) %>
				<p>Seleccione el fondo de la Base:</p>
				<%= f.select(:base_diploma_fondo, options_for_select(@paquete[:base][:fondo].each do |x| [x] end)) %>
				<p>Seleccione si la base es Plana o 3D:</p>
				<%= f.radio_button :base_diploma_3d, '' %>
				<%= f.label :base_diploma_3d, 'Plana', :value => '' %>
				<%= f.radio_button :base_diploma_3d, '3D' %>
				<%= f.label :base_diploma_3d, '3D', :value => '3D' %>
			</div>
			<div class="col-md-6">
				<h5>Placa Diploma</h5>
				<p>Seleccione el Tipo de Placa:</p>
				<%= f.select(:placa_diploma, options_for_select(@paquete[:base][:placa][:tipo].each do |x| [x] end)) %>
				<p>Seleccione el Color de Placa:</p>
				<%= f.select(:placa_diploma_color, options_for_select(@paquete[:base][:placa][:color].each do |x| [x] end)) %>
			</div>
		</div>


		<div class="row main">
			<div class="col-md-6">
				<h3>Fotografía</h3>
				<p>Seleccione la base de la Fotografía:</p>
				<%= f.select(:base_foto, options_for_select(@paquete[:base][:tipo].each do |x| [x] end)) %>			
				<p>Seleccione el color de la Base:</p>
				<%= f.select(:base_foto_color, options_for_select(@paquete[:base][:color].each do |x| [x] end)) %>
				<p>Seleccione el tamaño de la Base:</p>			
				<%= f.select(:base_foto_tamaño, options_for_select(@paquete[:base][:tamaño].each do |x| [x] end)) %>
				<p>Seleccione el fondo de la Base:</p>
				<%= f.select(:base_foto_fondo, options_for_select(@paquete[:base][:fondo].each do |x| [x] end)) %>
				<p>Seleccione si la base es Plana o 3D:</p>
				<%= f.radio_button :base_foto_3d, '' %>
				<%= f.label :base_foto_3d, 'Plana', :value => '' %>
				<%= f.radio_button :base_foto_3d, '3D' %>
				<%= f.label :base_foto_3d, '3D', :value => '3D' %>
			</div>
			<div class="col-md-6">
				<h5>Placa Fotografía</h5>
				<p>Seleccione el Tipo de Placa:</p>
				<%= f.select(:placa_foto, options_for_select(@paquete[:base][:placa][:tipo].each do |x| [x] end)) %>
				<p>Seleccione el Color de Placa:</p>
				<%= f.select(:placa_foto_color, options_for_select(@paquete[:base][:placa][:color].each do |x| [x] end)) %>
			</div>
		</div>

		
		<div class="row last">
			<div class="col-md-10">
				<h3>Anillo</h3>
				<p>Seleccione el Modelo de Anillo:</p>
				<%= f.select(:anillo, options_for_select(@paquete[:anillo][:nombre].each do |x| [x] end)) %></br>
				<p>Seleccione el Tamaño de Anillo:</p>
				<%= f.select(:anillo_tamaño, options_for_select(@paquete[:anillo][:tamaño].each do |x| [x] end), {}, {:class => 'tamaño'}) %><br>
			</div>
		</div>


		<%= f.hidden_field :group_id, :value => @group.id %>
		<%= f.submit 'Actualizar'%>
		<% end %>
	</div>
</div>

app/views/package/show.html.erb
<div class="package">
	<div class="container">
		
		<div class="row">
			<div class="col-md-12">
				<%= link_to 'Editar Pedido', update_path(@student), :class => 'link' %>
			</div>
		</div>

	</div>
</div>

app/views/students/create.html.erb
<div class="agregar_pedido">
	<div class="container">
		<h2>Agregar pedido a <%= @group.degree.titleize %> <%= link_to @group.representative.titleize, show_group_path %></h2>
		
		<%= form_for(@student, url: create_student_path) do |f| %>
		
		<div class="row">
			<div class="col-md-12">				
				<span><%= f.text_field :name, :required => 'required', :placeholder => 'Nombre', :class => 'nombre' %><br>
				<%= f.email_field :email, :required => 'required', :placeholder => 'Email' %>
				<%= f.text_field :cellphone, :placeholder => 'Celular' %><br></span>
			</div>
		</div>
		
		<div class="row first main">
			<div class="col-md-6">
				<h3>Agradecimiento</h3>
				<p>Seleccione la base de la Agradecimiento:</p>
				<%= f.select(:base_agradecimiento, options_for_select(@paquete[:base][:tipo].each do |x| [x] end)) %>			
				<p>Seleccione el color de la Base:</p>
				<%= f.select(:base_agradecimiento_color, options_for_select(@paquete[:base][:color].each do |x| [x] end)) %>
				<p>Seleccione el tamaño de la Base:</p>			
				<%= f.select(:base_agradecimiento_tamaño, options_for_select(@paquete[:base][:tamaño].each do |x| [x] end)) %>
				<p>Seleccione el fondo de la Base:</p>
				<%= f.select(:base_agradecimiento_fondo, options_for_select(@paquete[:base][:fondo].each do |x| [x] end)) %>
				<p>Seleccione si la base es Plana o 3D:</p>
				<%= f.radio_button :base_agradecimiento_3d, '' %>
				<%= f.label :base_agradecimiento_3d, 'Plana', :value => '' %>
				<%= f.radio_button :base_agradecimiento_3d, '3D' %>
				<%= f.label :base_agradecimiento_3d, '3D', :value => '3D' %>
			</div>
			<div class="col-md-6">
				<h5>Placa Agradecimiento</h5>
				<p>Seleccione el Tipo de Placa:</p>
				<%= f.select(:placa_agradecimiento, options_for_select(@paquete[:base][:placa][:tipo].each do |x| [x] end)) %>
				<p>Seleccione el Color de Placa:</p>
				<%= f.select(:placa_agradecimiento_color, options_for_select(@paquete[:base][:placa][:color].each do |x| [x] end)) %>
			</div>
		</div>
		

		<div class="row main">
			<div class="col-md-6">
				<h3>Diploma</h3>
				<p>Seleccione la base del Diploma:</p>
				<%= f.select(:base_diploma, options_for_select(@paquete[:base][:tipo].each do |x| [x] end)) %>			
				<p>Seleccione el color de la Base:</p>
				<%= f.select(:base_diploma_color, options_for_select(@paquete[:base][:color].each do |x| [x] end)) %>
				<p>Seleccione el tamaño de la Base:</p>			
				<%= f.select(:base_diploma_tamaño, options_for_select(@paquete[:base][:tamaño].each do |x| [x] end)) %>
				<p>Seleccione el fondo de la Base:</p>
				<%= f.select(:base_diploma_fondo, options_for_select(@paquete[:base][:fondo].each do |x| [x] end)) %>
				<p>Seleccione si la base es Plana o 3D:</p>
				<%= f.radio_button :base_diploma_3d, '' %>
				<%= f.label :base_diploma_3d, 'Plana', :value => '' %>
				<%= f.radio_button :base_diploma_3d, '3D' %>
				<%= f.label :base_diploma_3d, '3D', :value => '3D' %>
			</div>
			<div class="col-md-6">
				<h5>Placa Diploma</h5>
				<p>Seleccione el Tipo de Placa:</p>
				<%= f.select(:placa_diploma, options_for_select(@paquete[:base][:placa][:tipo].each do |x| [x] end)) %>
				<p>Seleccione el Color de Placa:</p>
				<%= f.select(:placa_diploma_color, options_for_select(@paquete[:base][:placa][:color].each do |x| [x] end)) %>
			</div>
		</div>


		<div class="row main">
			<div class="col-md-6">
				<h3>Fotografía</h3>
				<p>Seleccione la base de la Fotografía:</p>
				<%= f.select(:base_foto, options_for_select(@paquete[:base][:tipo].each do |x| [x] end)) %>			
				<p>Seleccione el color de la Base:</p>
				<%= f.select(:base_foto_color, options_for_select(@paquete[:base][:color].each do |x| [x] end)) %>
				<p>Seleccione el tamaño de la Base:</p>			
				<%= f.select(:base_foto_tamaño, options_for_select(@paquete[:base][:tamaño].each do |x| [x] end)) %>
				<p>Seleccione el fondo de la Base:</p>
				<%= f.select(:base_foto_fondo, options_for_select(@paquete[:base][:fondo].each do |x| [x] end)) %>
				<p>Seleccione si la base es Plana o 3D:</p>
				<%= f.radio_button :base_foto_3d, '' %>
				<%= f.label :base_foto_3d, 'Plana', :value => '' %>
				<%= f.radio_button :base_foto_3d, '3D' %>
				<%= f.label :base_foto_3d, '3D', :value => '3D' %>
			</div>
			<div class="col-md-6">
				<h5>Placa Fotografía</h5>
				<p>Seleccione el Tipo de Placa:</p>
				<%= f.select(:placa_foto, options_for_select(@paquete[:base][:placa][:tipo].each do |x| [x] end)) %>
				<p>Seleccione el Color de Placa:</p>
				<%= f.select(:placa_foto_color, options_for_select(@paquete[:base][:placa][:color].each do |x| [x] end)) %>
			</div>
		</div>

		
		<div class="row last">
			<div class="col-md-10">
				<h3>Anillo</h3>
				<p>Seleccione el Modelo de Anillo:</p>
				<%= f.select(:anillo, options_for_select(@paquete[:anillo][:nombre].each do |x| [x] end)) %></br>
				<p>Seleccione el Tamaño de Anillo:</p>
				<%= f.select(:anillo_tamaño, options_for_select(@paquete[:anillo][:tamaño].each do |x| [x] end), {}, {:class => 'tamaño'}) %><br>
			</div>
		</div>


		<%= f.hidden_field :group_id, :value => @group.id %>
		<%= f.submit 'Guardar'%>
		<% end %>
	</div>
</div>

app/views/students/show.html.erb
<div class="generar_material">
	<div class="container">
		<div class="row">
			<div class="col-md-12" align="center">
				<table>
					<tr>
						<th class="grupo" colspan="2" style="text-align: center; font-size: 1.5em;">Material para <%= @group.degree.titleize %> <%= link_to @group.representative.titleize, show_group_path %></th>
					</tr>
					<tr>
						<th class="de" colspan="2" style="text-align: center; font-size: 1.4em;">Agradecimientos</th>
					</tr>
					<tr>
						<th>Base</th>
						<th style="text-align: center;">Cantidad</th>
					</tr>
					<% @base_agradecimiento.each do |key, value| %>
					<tr>
						<td><%= key %></td>
						<td align="center"><%= value%></td>
					</tr>
					<% end %>
					<tr>
						<th class="de" colspan="2" style="text-align: center; font-size: 1.4em;">Diplomas</th>
					</tr>
					<tr>
						<th>Base</th>
						<th style="text-align: center;">Cantidad</th>
					</tr>
					<% @base_diploma.each do |key, value| %>
					<tr>
						<td><%= key %></td>
						<td align="center"><%= value%></td>
					</tr>
					<% end %>
					<tr>
						<th class="de" colspan="2" style="text-align: center; font-size: 1.4em;">Fotografías</th>
					</tr>
					<tr>
						<th>Base</th>
						<th style="text-align: center;">Cantidad</th>
					</tr>
					<% @base_foto.each do |key, value| %>
					<tr>
						<td><%= key %></td>
						<td align="center"><%= value%></td>
					</tr>
					<% end %>
				</table>
			</div>
		</div>
	</div>
</div>